# Generated by Django 4.1.1 on 2022-11-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatroom_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
